version: '3'

services:
  airflow:
    image: airflow:latest
  
    volumes:
      - ./airflow:/opt/airflow
      - ./db:/usr/local/airflow/db

    ports:
      - "8080:8080"

    command: airflow standalone